{{ $data := $.Site.Data.xrp -}}
[METADATA]
modified = {{ .Lastmod | time.Format "2006-01-02T15:04:05Z" }}
{{ if $data.expires -}}
expires = {{ $data.expires }}
{{- end }}

{{ range $data.validators -}}
[[VALIDATORS]]
public_key = "{{ .public_key }}"
attestation = "{{ .attestation }}"
network = "{{ .network }}"
owner_country = "{{ .owner_country }}"
server_country = "{{ .server_country }}"
unl = "{{ .unl }}"
{{- end }}

{{ range $data.servers -}}
[[SERVERS]]
public_key = "{{ .public_key }}"
attestation = "{{ .attestation }}"
network = "{{ .network }}"
owner_country = "{{ .owner_country }}"
server_country = "{{ .server_country }}"
unl = "{{ .unl }}"
{{- end }}

{{ range $data.principals -}}
[[PRINCIPALS]]
name = "{{ .name }}"
email = "{{ .email }}"
{{- end }}

# End of file